/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    public Calculator() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        oct1 = new javax.swing.JTextField();
        oct2 = new javax.swing.JTextField();
        oct3 = new javax.swing.JTextField();
        oct4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mask = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb1 = new javax.swing.JTable();
        calcular = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mask_custom = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        novo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        sair = new javax.swing.JMenuItem();
        sobre = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("IP:");

        oct1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oct1KeyReleased(evt);
            }
        });

        oct2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oct2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oct2KeyReleased(evt);
            }
        });

        oct3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oct3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oct3KeyReleased(evt);
            }
        });

        oct4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oct4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oct4KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("/");

        mask.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                maskKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maskKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Engravers MT", 0, 11)); // NOI18N
        jLabel3.setText("Entre com o IP / Mask");

        jtb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rede", "Intervalo", "Broadcast"
            }
        ));
        jScrollPane1.setViewportView(jtb1);

        calcular.setText("Calcular");
        calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularMouseClicked(evt);
            }
        });
        calcular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calcularKeyPressed(evt);
            }
        });

        jLabel4.setText("Mask:");

        mask_custom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jMenu1.setText("Iniciar");

        novo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        jMenu1.add(novo);
        jMenu1.add(jSeparator3);

        sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        sobre.setText("Sobre");
        sobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(oct1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(oct2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(oct3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(oct4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mask, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(calcular))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mask_custom)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(oct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oct2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oct3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oct4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(mask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calcular))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mask_custom))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        
    }//GEN-LAST:event_novoActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        
    }//GEN-LAST:event_sairActionPerformed

    private void calcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularMouseClicked

        DefaultTableModel model = (DefaultTableModel) jtb1.getModel();
            model.setRowCount(0);
        mask_custom.setText("");
        
        int re4=0, bro4=0, sub1 = 0, sub2 = 0;
        int oct1dec, oct2dec, oct3dec, oct4dec, maskdec, host,op;
        boolean erro = false;
        String rede,intervalo,broadcast;   
        
        try{
            op = Integer.parseInt(oct1.getText());
        }catch(NumberFormatException ex){
            erro = true;
        }
        try{
            op = Integer.parseInt(oct2.getText());
        }catch(NumberFormatException ex){
            erro = true;
        }
        try{
            op = Integer.parseInt(oct3.getText());
        }catch(NumberFormatException ex){
            erro = true;
        }
        try{
            op = Integer.parseInt(oct4.getText());
        }catch(NumberFormatException ex){
            erro = true;
        }
        try{
            op = Integer.parseInt(mask.getText());
        }catch(NumberFormatException ex){
            erro = true;
        }

        if (erro == true){
            JOptionPane.showMessageDialog(null, "Ip inválido!","Erro!",JOptionPane.ERROR_MESSAGE);
        }
        else{
            //transformar string em inteiro (dec)
            oct1dec = Integer.parseInt(oct1.getText());
            oct2dec = Integer.parseInt(oct2.getText());
            oct3dec = Integer.parseInt(oct3.getText());
            oct4dec = Integer.parseInt(oct4.getText());
            maskdec = Integer.parseInt(mask.getText());
        }
    }//GEN-LAST:event_calcularMouseClicked

    private void oct1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oct1KeyReleased
        if(oct1.getText().length() == 3)
            oct2.requestFocus();
    }//GEN-LAST:event_oct1KeyReleased

    private void oct2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oct2KeyReleased
        if(oct2.getText().length() == 3)
            oct3.requestFocus();
    }//GEN-LAST:event_oct2KeyReleased

    private void oct3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oct3KeyReleased
        if(oct3.getText().length() == 3)
            oct4.requestFocus();
    }//GEN-LAST:event_oct3KeyReleased

    private void oct4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oct4KeyReleased
        if(oct4.getText().length() == 3)
            mask.requestFocus();
    }//GEN-LAST:event_oct4KeyReleased

    private void maskKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maskKeyReleased
        if(mask.getText().length() == 2)
            calcular.requestFocus();
    }//GEN-LAST:event_maskKeyReleased

    private void oct2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oct2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            oct3.requestFocus();
        }
    }//GEN-LAST:event_oct2KeyPressed

    private void oct3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oct3KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            oct4.requestFocus();
        }
    }//GEN-LAST:event_oct3KeyPressed

    private void oct4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oct4KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            mask.requestFocus();
        }
    }//GEN-LAST:event_oct4KeyPressed

    private void maskKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maskKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calcular.requestFocus();
        }
    }//GEN-LAST:event_maskKeyPressed

    private void calcularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calcularKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            calcularMouseClicked(null);
        }
    }//GEN-LAST:event_calcularKeyPressed

    private void sobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobreMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Sobre sob = new Sobre();
        sob.setVisible(true);
    }//GEN-LAST:event_sobreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jtb1;
    private javax.swing.JTextField mask;
    private javax.swing.JLabel mask_custom;
    private javax.swing.JMenuItem novo;
    private javax.swing.JTextField oct1;
    private javax.swing.JTextField oct2;
    private javax.swing.JTextField oct3;
    private javax.swing.JTextField oct4;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenu sobre;
    // End of variables declaration//GEN-END:variables
}
